Repository UMass-Rescue/ImageSearch_CLIP, pull requests merged in 2024-11, with the labels that each got.

#71 Ensure Embeddings Are Moved to CPU Before Passing to FAISS
  model.py
Labels: bug

#73 Added Normalization for Cosine Similarity in FAISS Indexing
  Pipfile
  db.py
Labels: bug

#74 Readme update
  README.md
Labels: documentation

#75 Fixing hardocded table name in database operations
  db.py
Labels: bug

#79 Refactor and Structure Code for Maintainability
  cli/cli_preprocess.py
  cli/cli_search.py
  database/faiss.py
  database/psql.py
  example/preprocess.py
  example/search.py
  model/model.py
  server/server.py
  util/util.py
Labels: enhancement

#81 Addressing edge cases like input validations
  model/model.py
  server/server.py
  util/util.py
Labels: enhancement

#84 Create app_info.md
  server/app_info.md
Labels: documentation, enhancement
